server:
  port: 8080

spring:
  application:
    name: toss-mydata-client

logging:
  level:
    org.springframework.web.cors: TRACE
    org.springframework.web.reactive: TRACE
    reactor.netty.http.client: TRACE
  webflux:
    webclient:
      codecs:
        max-in-memory-size: 1MB